variables:
  majorVersion: '1'
  minorVersion: '3'
  buildConfiguration: 'Release'
  projectName: 'ThomasMathers.Infrastructure.ResponseWrapping'

name: '$(majorVersion).$(minorVersion).$(Rev:r)'

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'